prooph_service_bus:
  command_buses:
    beer_command_bus:
      router:
        type: 'prooph_service_bus.command_bus_router'
        routes:
          Webbaard\BeerWarehouse\Domain\Beer\Command\BuyBeer::class:
            Webbaard\BeerWarehouse\Domain\Beer\CommandHandler\BuyBeerHandler
          Webbaard\BeerWarehouse\Domain\Beer\Command\ConsumeBeer::class:
            Webbaard\BeerWarehouse\Domain\Beer\CommandHandler\ConsumeBeerHandler
          Webbaard\BeerWarehouse\Domain\Beer\Command\MoveBeer::class:
            Webbaard\BeerWarehouse\Domain\Beer\CommandHandler\MoveBeerHandler
          Webbaard\BeerWarehouse\Domain\Beer\Command\RemoveBeer::class:
            Webbaard\BeerWarehouse\Domain\Beer\CommandHandler\RemoveBeerHandler
    location_command_bus:
      router:
        type: 'prooph_service_bus.command_bus_router'
        routes:
          Webbaard\BeerWarehouse\Domain\Location\Command\AddLocation::class:
            Webbaard\BeerWarehouse\Domain\Location\CommandHandler\AddLocationHandler
          Webbaard\BeerWarehouse\Domain\Location\Command\RemoveLocation::class:
            Webbaard\BeerWarehouse\Domain\Location\CommandHandler\RemoveLocationHandler
    style_command_bus:
      router:
        type: 'prooph_service_bus.command_bus_router'
        routes:
          Webbaard\BeerWarehouse\Domain\Style\Command\AddStyle::class:
            Webbaard\BeerWarehouse\Domain\Style\CommandHandler\AddStyleHandler
          Webbaard\BeerWarehouse\Domain\Style\Command\RemoveStyle::class:
            Webbaard\BeerWarehouse\Domain\Style\CommandHandler\RemoveStyleHandler
  event_buses:
    beer_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'
