prooph_event_store:
    stores:
        beer_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                beer_collection:
                    repository_class: Webbaard\BeerWarehouse\Infra\Beer\Repository\BeerRepository
                    aggregate_type: Webbaard\BeerWarehouse\Domain\Beer\Beer
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
        location_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                location_collection:
                    repository_class: Webbaard\BeerWarehouse\Infra\Beer\Repository\LocationRepository
                    aggregate_type: Webbaard\BeerWarehouse\Domain\Location\Location
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
        style_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                style_collection:
                    repository_class: Webbaard\BeerWarehouse\Infra\Beer\Repository\StyleRepository
                    aggregate_type: Webbaard\BeerWarehouse\Domain\Style\Style
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
    projection_managers:
        beer_projection_manager:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore # event store
            connection: 'doctrine.pdo.connection'
            projections:
                beer_projection:
                    read_model: Webbaard\BeerWarehouse\Infra\Beer\Projection\Beer\BeerReadModel
                    projection: Webbaard\BeerWarehouse\Infra\Beer\Projection\Beer\BeerProjection
        location_projection_manager:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore # event store
            connection: 'doctrine.pdo.connection'
            projections:
                location_projection:
                    read_model: Webbaard\BeerWarehouse\Infra\Beer\Projection\Location\LocationReadModel
                    projection: Webbaard\BeerWarehouse\Infra\Beer\Projection\Location\LocationProjection
        style_projection_manager:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore # event store
            connection: 'doctrine.pdo.connection'
            projections:
                style_projection:
                    read_model: Webbaard\BeerWarehouse\Infra\Beer\Projection\Style\StyleReadModel
                    projection: Webbaard\BeerWarehouse\Infra\Beer\Projection\Style\StyleProjection
services:
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator